---
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: yarn dev
      - run: yarn run percy exec -- cypress run
      - run: echo "Hello"
