---
version: 2.1
orbs:
  node: circleci/node@5.0.0
jobs:
  build:
    #docker:
      #- image: 'cypress/base:14'
    machine:
      image: ubuntu-2004:202010-01 
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '17.3'
      - run: node --version
      - run: ls
      - run: yarn install
      - run:
          name: localhost
          command: yarn dev && sleep 10
          background: true
      - run: yarn run percy exec -- cypress run
      - run: yarn percy snapshot .circleci/www.yml
